import Foundation

enum LorixFleverText {
    static let hexByteWithDot = "%02.2hhx"
    static let hexByte = "%02hhx"
    static let deviceSeed = "lorix.flever.device.seed"
    static let passwordSeed = "lorix.flever.password.seed"
    static let infoIcon = "info.circle"
    static let successIcon = "checkmark.circle.fill"
    static let loading = "Loading..."
    static let openValue = "openValue"
    static let loginFlag = "loginFlag"
    static let token = "token"
    static let timestamp = "timestamp"
    static let openParamsJoiner = "/?openParams="
    static let appIDJoiner = "&appId="
    static let quickLogin = "Quickly Log"
    static let invalidLogin = "Login info invalid!"
    static let password = "password"
    static let cannotPay = "In-App Purchases are disabled on this device."
    static let missingProduct = "No valid product found."
    static let paymentCancelled = "Payment cancelled"
    static let transactionFailed = "Transaction failed."
    static let paySuccess = "Pay Successful"
    static let urlError = "URL Error"
    static let post = "POST"
    static let contentType = "Content-Type"
    static let appID = "appId"
    static let appVersion = "appVersion"
    static let json = "application/json"
    static let deviceNo = "deviceNo"
    static let language = "language"
    static let loginToken = "loginToken"
    static let pushToken = "pushToken"
    static let noData = "No Data"
    static let invalidJSON = "Invalid JSON"
    static let code = "code"
    static let successCode = "0000"
    static let payError = "Pay Error"
    static let result = "result"
    static let message = "message"
    static let dataError = "Data Back Error"
    static let decryptError = "Decryption Error"
    static let versionKey = "CFBundleShortVersionString"
    static let rechargePay = "rechargePay"
    static let close = "Close"
    static let pageLoaded = "pageLoaded"
    static let batchNo = "batchNo"
    static let orderCode = "orderCode"
    static let paying = "Paying..."
    static let payFailed = "Pay failed"
    static let totalPrice = "totalPrice"
    static let currency = "currency"
    static let usd = "USD"
    static let purchaseBusy = "The payment is in progress, please wait for completion."
    static let parentalPending = "Payment pending parental approval"
    static let openBrowser = "openBrowser"
    static let url = "url"
    static let facebookPurchaseFlag = "fb_mobile_purchase"
    static let trueValue = "true"
    static let networkQueue = "lorix.flever.network.queue"
}

enum LorixFleverStorageKey {
    private static var prefix: String {
        let bundle = Bundle.main.bundleIdentifier ?? "com.lorix.flever"
        return "\(bundle).lorix.flever."
    }
    
    static let pushToken = prefix + "pushToken"
    static let userToken = prefix + "userToken"
    static let openValue = prefix + "openValue"
    static let didRequestGate = prefix + "didRequestGate"
    static let adjustID = prefix + "adjustID"
    static let adjustPayload = prefix + "adjustPayload"
}
